# Generated by Django 4.2.30 on 2026-07-09 16:04

import conciliacao.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "financeiro",
            "0004_historicalreceitaaluguel_historicalfechamentomensal_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patrimonio", "0006_historicalcontrato_historicalcontratoparte_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConciliacaoReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_atribuido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Atribuído (R$)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conciliacoes",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Conciliada",
                "verbose_name_plural": "Receitas Conciliadas",
            },
        ),
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='Ex.: "Itaú PJ Holding".',
                        max_length=100,
                        verbose_name="Nome / Apelido",
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=20, verbose_name="Agência"),
                ),
                (
                    "numero_conta",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Número da Conta"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ExtratoImportado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=conciliacao.models.upload_extrato_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["ofx", "qfx"]
                            )
                        ],
                        verbose_name="Arquivo OFX",
                    ),
                ),
                (
                    "hash_arquivo",
                    models.CharField(
                        help_text="SHA-256 do conteúdo — impede importar o mesmo arquivo duas vezes.",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash do Arquivo",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início do Período"
                    ),
                ),
                (
                    "periodo_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do Período"
                    ),
                ),
                (
                    "transacoes_novas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Transações Novas"
                    ),
                ),
                (
                    "transacoes_duplicadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Transações Duplicadas (ignoradas)"
                    ),
                ),
                (
                    "importado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Importado em"
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extratos",
                        to="conciliacao.contabancaria",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrato Importado",
                "verbose_name_plural": "Extratos Importados",
                "ordering": ["-importado_em"],
            },
        ),
        migrations.CreateModel(
            name="TransacaoExtrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fitid",
                    models.CharField(
                        help_text="Identificador único da transação no OFX — garante que reimportações não dupliquem.",
                        max_length=255,
                        verbose_name="FITID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negativo para débitos, como vem no extrato.",
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("credito", "Crédito"), ("debito", "Débito")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição"
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=300, verbose_name="Memo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("conciliada", "Conciliada"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="pendente",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacoes",
                        to="conciliacao.contabancaria",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacoes_extrato",
                        to="financeiro.despesa",
                        verbose_name="Despesa Lançada",
                    ),
                ),
                (
                    "extrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes",
                        to="conciliacao.extratoimportado",
                        verbose_name="Extrato",
                    ),
                ),
                (
                    "receitas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transacoes_extrato",
                        through="conciliacao.ConciliacaoReceita",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receitas Conciliadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação do Extrato",
                "verbose_name_plural": "Transações do Extrato",
                "ordering": ["data", "id"],
                "unique_together": {("conta", "fitid")},
            },
        ),
        migrations.CreateModel(
            name="RegraClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_contem",
                    models.CharField(
                        help_text='Trecho procurado (sem diferenciar maiúsculas) na descrição/memo da transação. Ex.: "CEMIG".',
                        max_length=100,
                        verbose_name="Descrição Contém",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("manutencao", "Manutenção"),
                            ("seguro", "Seguro"),
                            ("taxa_bancaria", "Taxa Bancária"),
                            ("contabilidade", "Contabilidade"),
                            ("advocacia", "Advocacia"),
                            ("comissao_imobiliaria", "Comissão Imobiliária"),
                            ("obra_reforma", "Obra / Reforma"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Categoria da Despesa",
                    ),
                ),
                (
                    "prioridade",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Menor número = avaliada primeiro.",
                        verbose_name="Prioridade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.pessoa",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Classificação",
                "verbose_name_plural": "Regras de Classificação",
                "ordering": ["prioridade", "texto_contem"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTransacaoExtrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fitid",
                    models.CharField(
                        help_text="Identificador único da transação no OFX — garante que reimportações não dupliquem.",
                        max_length=255,
                        verbose_name="FITID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negativo para débitos, como vem no extrato.",
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("credito", "Crédito"), ("debito", "Débito")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição"
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=300, verbose_name="Memo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("conciliada", "Conciliada"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="pendente",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="conciliacao.contabancaria",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="financeiro.despesa",
                        verbose_name="Despesa Lançada",
                    ),
                ),
                (
                    "extrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="conciliacao.extratoimportado",
                        verbose_name="Extrato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Transação do Extrato",
                "verbose_name_plural": "historical Transações do Extrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRegraClassificacao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "texto_contem",
                    models.CharField(
                        help_text='Trecho procurado (sem diferenciar maiúsculas) na descrição/memo da transação. Ex.: "CEMIG".',
                        max_length=100,
                        verbose_name="Descrição Contém",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("manutencao", "Manutenção"),
                            ("seguro", "Seguro"),
                            ("taxa_bancaria", "Taxa Bancária"),
                            ("contabilidade", "Contabilidade"),
                            ("advocacia", "Advocacia"),
                            ("comissao_imobiliaria", "Comissão Imobiliária"),
                            ("obra_reforma", "Obra / Reforma"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Categoria da Despesa",
                    ),
                ),
                (
                    "prioridade",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Menor número = avaliada primeiro.",
                        verbose_name="Prioridade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.pessoa",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Regra de Classificação",
                "verbose_name_plural": "historical Regras de Classificação",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExtratoImportado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["ofx", "qfx"]
                            )
                        ],
                        verbose_name="Arquivo OFX",
                    ),
                ),
                (
                    "hash_arquivo",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 do conteúdo — impede importar o mesmo arquivo duas vezes.",
                        max_length=64,
                        verbose_name="Hash do Arquivo",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início do Período"
                    ),
                ),
                (
                    "periodo_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do Período"
                    ),
                ),
                (
                    "transacoes_novas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Transações Novas"
                    ),
                ),
                (
                    "transacoes_duplicadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Transações Duplicadas (ignoradas)"
                    ),
                ),
                (
                    "importado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Importado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="conciliacao.contabancaria",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Extrato Importado",
                "verbose_name_plural": "historical Extratos Importados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContaBancaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='Ex.: "Itaú PJ Holding".',
                        max_length=100,
                        verbose_name="Nome / Apelido",
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=20, verbose_name="Agência"),
                ),
                (
                    "numero_conta",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Número da Conta"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Conta Bancária",
                "verbose_name_plural": "historical Contas Bancárias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="conciliacaoreceita",
            name="transacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_receita",
                to="conciliacao.transacaoextrato",
                verbose_name="Transação",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conciliacaoreceita",
            unique_together={("transacao", "receita")},
        ),
    ]
