# Generated by Django 4.2.30 on 2026-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciliacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="bank_id",
            field=models.CharField(
                blank=True,
                help_text="Código BANKID que aparece no arquivo OFX (ex.: 0341). Se preenchido, é conferido na importação.",
                max_length=20,
                verbose_name="Código do Banco (OFX)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontabancaria",
            name="bank_id",
            field=models.CharField(
                blank=True,
                help_text="Código BANKID que aparece no arquivo OFX (ex.: 0341). Se preenchido, é conferido na importação.",
                max_length=20,
                verbose_name="Código do Banco (OFX)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransacaoextrato",
            name="comissoes_marcadas",
            field=models.BooleanField(
                default=False,
                help_text="Indica que esta conciliação (repasse líquido) marcou despesas de comissão como pagas — usado ao desfazer.",
                verbose_name="Comissões Marcadas como Pagas",
            ),
        ),
        migrations.AddField(
            model_name="transacaoextrato",
            name="comissoes_marcadas",
            field=models.BooleanField(
                default=False,
                help_text="Indica que esta conciliação (repasse líquido) marcou despesas de comissão como pagas — usado ao desfazer.",
                verbose_name="Comissões Marcadas como Pagas",
            ),
        ),
        migrations.AlterField(
            model_name="contabancaria",
            name="numero_conta",
            field=models.CharField(
                blank=True,
                help_text="Se preenchido, é conferido (só dígitos) com o ACCTID do arquivo OFX na importação.",
                max_length=30,
                verbose_name="Número da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontabancaria",
            name="numero_conta",
            field=models.CharField(
                blank=True,
                help_text="Se preenchido, é conferido (só dígitos) com o ACCTID do arquivo OFX na importação.",
                max_length=30,
                verbose_name="Número da Conta",
            ),
        ),
    ]
