# Generated by Django 4.2.30 on 2026-07-11 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_migrar_recebimentos_iniciais"),
        ("conciliacao", "0002_contabancaria_bank_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conciliacaoreceita",
            name="valor_atribuido",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Parcela do crédito bancário atribuída a esta receita (líquida de comissão no repasse líquido).",
                max_digits=12,
                verbose_name="Valor Atribuído do Crédito (R$)",
            ),
        ),
        migrations.CreateModel(
            name="ConciliacaoComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor da Comissão (R$)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conciliacoes_comissao",
                        to="financeiro.despesa",
                        verbose_name="Despesa de Comissão",
                    ),
                ),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_comissao",
                        to="conciliacao.transacaoextrato",
                        verbose_name="Transação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissão Conciliada",
                "verbose_name_plural": "Comissões Conciliadas",
            },
        ),
        migrations.AddConstraint(
            model_name="conciliacaocomissao",
            constraint=models.UniqueConstraint(
                fields=("transacao", "despesa"),
                name="conciliacaocomissao_transacao_despesa_unica",
            ),
        ),
    ]
