# Generated by Django 4.2.30 on 2026-07-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_validacoes_monetarias"),
        ("conciliacao", "0003_alter_conciliacaoreceita_valor_atribuido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conciliacaocomissao",
            name="despesa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciliacoes_comissao",
                to="financeiro.despesa",
                verbose_name="Despesa de Comissão",
            ),
        ),
    ]
