# Generated by Django 4.2.30 on 2026-07-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_validacoes_despesa"),
        ("conciliacao", "0004_conciliacaocomissao_despesa_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacaoextrato",
            name="despesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes_extrato",
                to="financeiro.despesa",
                verbose_name="Despesa Lançada",
            ),
        ),
    ]
