# Generated by Django 4.2.30 on 2026-07-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conciliacao", "0005_transacaoextrato_despesa_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacaoextrato",
            name="extrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes",
                to="conciliacao.extratoimportado",
                verbose_name="Extrato",
            ),
        ),
    ]
