# Generated by Django 4.2.30 on 2026-07-13 05:21
"""
Prova de origem explícita da despesa de um débito conciliado: nenhuma
inferência sobre dados existentes. AddField(default=False) preenche TODOS
os registros antigos com despesa_criada_pela_conciliacao=False — inclusive
transações que já têm uma despesa vinculada e são compatíveis em valor/
data/status. Essa compatibilidade nunca é tratada como prova; a origem
dessas despesas permanece desconhecida até revisão humana (fora do escopo
desta tarefa). Por partir de False para todo mundo, nenhuma pré-checagem de
dados é necessária — a CheckConstraint abaixo é satisfeita automaticamente
por qualquer registro com o campo em False, independentemente do estado de
`despesa`/`tipo`.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciliacao", "0006_transacaoextrato_extrato_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransacaoextrato",
            name="despesa_criada_pela_conciliacao",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text='True declara que a despesa atualmente vinculada em "despesa" foi criada pelo próprio lancar_despesa() para esta transação — única prova de origem aceita para excluí-la automaticamente ao desfazer a conciliação. Nunca inferido por coincidência de valor/data/status; controlado exclusivamente pelos services de conciliação (lancar_despesa()/desfazer_conciliacao()).',
                verbose_name="Despesa Criada pela Conciliação",
            ),
        ),
        migrations.AddField(
            model_name="transacaoextrato",
            name="despesa_criada_pela_conciliacao",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text='True declara que a despesa atualmente vinculada em "despesa" foi criada pelo próprio lancar_despesa() para esta transação — única prova de origem aceita para excluí-la automaticamente ao desfazer a conciliação. Nunca inferido por coincidência de valor/data/status; controlado exclusivamente pelos services de conciliação (lancar_despesa()/desfazer_conciliacao()).',
                verbose_name="Despesa Criada pela Conciliação",
            ),
        ),
        migrations.AddConstraint(
            model_name="transacaoextrato",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("despesa_criada_pela_conciliacao", False),
                    models.Q(("despesa__isnull", False), ("tipo", "debito")),
                    _connector="OR",
                ),
                name="transacaoextrato_origem_despesa_exige_debito_vinculado",
            ),
        ),
    ]
