# Generated by Django 4.2.16 on 2026-06-26 19:25

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financeiro", "0001_initial"),
        ("patrimonio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("matricula", "Matrícula"),
                            ("contrato_aluguel", "Contrato de Aluguel"),
                            ("iptu", "IPTU"),
                            ("comprovante_pagamento", "Comprovante de Pagamento"),
                            ("nota_fiscal", "Nota Fiscal"),
                            ("declaracao_imobiliaria", "Declaração de Imóvel"),
                            ("extrato_bancario", "Extrato Bancário"),
                            ("seguro", "Seguro"),
                            ("laudo", "Laudo / Vistoria"),
                            ("procuracao", "Procuração"),
                            ("documento_contabil", "Documento Contábil"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=documentos.models.upload_documento_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Documento"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "enviado_contabilidade",
                    models.BooleanField(
                        default=False, verbose_name="Enviado à Contabilidade"
                    ),
                ),
                (
                    "data_envio_contabilidade",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Envio à Contabilidade",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.despesa",
                        verbose_name="Despesa",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita de Aluguel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
