# Generated by Django 4.2.16 on 2026-06-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0002_dia_vencimento_validators"),
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoObrigatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("matricula", "Matrícula"),
                            ("iptu", "IPTU"),
                            ("contrato_atual", "Contrato Atual"),
                            ("laudo_vistoria", "Laudo de Vistoria"),
                            ("seguro", "Seguro"),
                            ("procuracao", "Procuração"),
                            ("documento_contabil", "Documento Contábil"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "obrigatorio",
                    models.BooleanField(default=True, verbose_name="Obrigatório"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obrigatorios",
                        to="documentos.documento",
                        verbose_name="Documento Vinculado",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_obrigatorios",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Obrigatório",
                "verbose_name_plural": "Documentos Obrigatórios",
                "ordering": ["imovel__nome", "tipo"],
                "unique_together": {("imovel", "tipo")},
            },
        ),
    ]
