# Generated by Django 4.2.16 on 2026-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0002_dia_vencimento_validators"),
        ("documentos", "0002_documentoobrigatorio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentoobrigatorio",
            unique_together={("imovel", "tipo", "descricao")},
        ),
    ]
