# Generated by Django 4.2.30 on 2026-07-07 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documentos.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0006_historicalcontrato_historicalcontratoparte_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "financeiro",
            "0004_historicalreceitaaluguel_historicalfechamentomensal_and_more",
        ),
        ("documentos", "0003_documentoobrigatorio_unique_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                help_text="Extensões aceitas: pdf, jpg, jpeg, png, webp, doc, docx, odt, xls, xlsx, ods, csv, txt, zip. Máx. 25 MB.",
                upload_to=documentos.models.upload_documento_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "doc",
                            "docx",
                            "odt",
                            "xls",
                            "xlsx",
                            "ods",
                            "csv",
                            "txt",
                            "zip",
                        ]
                    ),
                    documentos.models.validar_tamanho_arquivo,
                ],
                verbose_name="Arquivo",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoObrigatorio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("matricula", "Matrícula"),
                            ("iptu", "IPTU"),
                            ("contrato_atual", "Contrato Atual"),
                            ("laudo_vistoria", "Laudo de Vistoria"),
                            ("seguro", "Seguro"),
                            ("procuracao", "Procuração"),
                            ("documento_contabil", "Documento Contábil"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "obrigatorio",
                    models.BooleanField(default=True, verbose_name="Obrigatório"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="documentos.documento",
                        verbose_name="Documento Vinculado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Documento Obrigatório",
                "verbose_name_plural": "historical Documentos Obrigatórios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("matricula", "Matrícula"),
                            ("contrato_aluguel", "Contrato de Aluguel"),
                            ("iptu", "IPTU"),
                            ("comprovante_pagamento", "Comprovante de Pagamento"),
                            ("nota_fiscal", "Nota Fiscal"),
                            ("declaracao_imobiliaria", "Declaração de Imóvel"),
                            ("extrato_bancario", "Extrato Bancário"),
                            ("seguro", "Seguro"),
                            ("laudo", "Laudo / Vistoria"),
                            ("procuracao", "Procuração"),
                            ("documento_contabil", "Documento Contábil"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        help_text="Extensões aceitas: pdf, jpg, jpeg, png, webp, doc, docx, odt, xls, xlsx, ods, csv, txt, zip. Máx. 25 MB.",
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "doc",
                                    "docx",
                                    "odt",
                                    "xls",
                                    "xlsx",
                                    "ods",
                                    "csv",
                                    "txt",
                                    "zip",
                                ]
                            ),
                            documentos.models.validar_tamanho_arquivo,
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Documento"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "enviado_contabilidade",
                    models.BooleanField(
                        default=False, verbose_name="Enviado à Contabilidade"
                    ),
                ),
                (
                    "data_envio_contabilidade",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Envio à Contabilidade",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="financeiro.despesa",
                        verbose_name="Despesa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita de Aluguel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Documento",
                "verbose_name_plural": "historical Documentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
