# Generated by Django 4.2.16 on 2026-06-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome / Identificação"
                    ),
                ),
                ("endereco", models.CharField(max_length=300, verbose_name="Endereço")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Matrícula"
                    ),
                ),
                (
                    "cartorio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cartório"
                    ),
                ),
                (
                    "inscricao_iptu",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inscrição IPTU"
                    ),
                ),
                (
                    "proprietario",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Proprietário(s)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alugado", "Alugado"),
                            ("vago", "Vago"),
                            ("em_manutencao", "Em Manutenção"),
                            ("vendido", "Vendido"),
                        ],
                        default="vago",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aquisicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aquisição"
                    ),
                ),
                (
                    "valor_aquisicao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor de Aquisição (R$)",
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Estimado Atual (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome / Razão Social"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("locatario", "Locatário"),
                            ("fiador", "Fiador"),
                            ("fornecedor", "Fornecedor"),
                            ("imobiliaria", "Imobiliária"),
                            ("contador", "Contador"),
                            ("advogado", "Advogado"),
                            ("familiar", "Familiar"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Endereço"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("eletrica", "Elétrica"),
                            ("hidraulica", "Hidráulica"),
                            ("pintura", "Pintura"),
                            ("reforma", "Reforma"),
                            ("limpeza", "Limpeza"),
                            ("telhado", "Telhado"),
                            ("estrutural", "Estrutural"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateField(verbose_name="Data da Solicitação"),
                ),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Estimado (R$)",
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Final (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("orcamento_recebido", "Orçamento Recebido"),
                            ("aprovada", "Aprovada"),
                            ("em_execucao", "Em Execução"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="solicitada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.pessoa",
                        verbose_name="Fornecedor / Prestador",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "ordering": ["-data_solicitacao"],
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Término")),
                (
                    "valor_aluguel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor do Aluguel (R$)",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.PositiveSmallIntegerField(verbose_name="Dia de Vencimento"),
                ),
                (
                    "indice_reajuste",
                    models.CharField(
                        choices=[
                            ("ipca", "IPCA"),
                            ("igpm", "IGP-M"),
                            ("inpc", "INPC"),
                            ("fixo", "Fixo"),
                            ("outro", "Outro"),
                        ],
                        default="ipca",
                        max_length=10,
                        verbose_name="Índice de Reajuste",
                    ),
                ),
                (
                    "data_proximo_reajuste",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Próximo Reajuste"
                    ),
                ),
                (
                    "tipo_garantia",
                    models.CharField(
                        choices=[
                            ("caucao", "Caução"),
                            ("fiador", "Fiador"),
                            ("seguro_fianca", "Seguro Fiança"),
                            ("titulo_capitalizacao", "Título de Capitalização"),
                            ("sem_garantia", "Sem Garantia"),
                            ("outro", "Outro"),
                        ],
                        default="sem_garantia",
                        max_length=30,
                        verbose_name="Tipo de Garantia",
                    ),
                ),
                (
                    "comissao_imobiliaria_percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Comissão Imobiliária (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("encerrado", "Encerrado"),
                            ("rescindido", "Rescindido"),
                            ("suspenso", "Suspenso"),
                        ],
                        default="ativo",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fiador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_como_fiador",
                        to="patrimonio.pessoa",
                        verbose_name="Fiador",
                    ),
                ),
                (
                    "imobiliaria",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "imobiliaria"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_como_imobiliaria",
                        to="patrimonio.pessoa",
                        verbose_name="Imobiliária",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
                (
                    "locatario",
                    models.ForeignKey(
                        limit_choices_to={"tipo__in": ["locatario", "outro"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_como_locatario",
                        to="patrimonio.pessoa",
                        verbose_name="Locatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-data_inicio"],
            },
        ),
    ]
