# Generated by Django 4.2.16 on 2026-06-28 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="dia_vencimento",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Dia de Vencimento",
            ),
        ),
    ]
