# Generated by Django 4.2.16 on 2026-07-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0002_dia_vencimento_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="data_encerramento_real",
            field=models.DateField(
                blank=True,
                help_text="Preencha apenas quando o contrato foi efetivamente encerrado (rescisão ou fim real da locação).",
                null=True,
                verbose_name="Data de Encerramento Real",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="dias_carencia_multa",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Número de dias após o vencimento antes de multa/juros começarem a incidir.",
                verbose_name="Dias de Carência para Multa",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="juros_mora_percentual_mes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de juros ao mês, calculado proporcionalmente aos dias de atraso (base 30 dias).",
                max_digits=6,
                verbose_name="Juros de Mora (% ao mês)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="multa_atraso_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de multa sobre o valor previsto, aplicado após os dias de carência.",
                max_digits=6,
                verbose_name="Multa por Atraso (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="prazo_indeterminado",
            field=models.BooleanField(
                default=False,
                help_text="Marque quando o contrato foi prorrogado por prazo indeterminado após o término original.",
                verbose_name="Prazo Indeterminado",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_pai",
            field=models.ForeignKey(
                blank=True,
                help_text="Preencha quando este imóvel for uma unidade vinculada a um prédio/imóvel maior (ex.: andar ou sala de um prédio).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades",
                to="patrimonio.imovel",
                verbose_name="Imóvel Pai",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="tipo_imovel",
            field=models.CharField(
                choices=[
                    ("apartamento", "Apartamento"),
                    ("casa", "Casa"),
                    ("sala_comercial", "Sala Comercial"),
                    ("loja", "Loja"),
                    ("predio", "Prédio"),
                    ("andar", "Andar"),
                    ("terreno", "Terreno"),
                    ("galpao", "Galpão"),
                    ("garagem", "Garagem"),
                    ("coworking", "Coworking"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
                verbose_name="Tipo de Imóvel",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="unidade_locavel",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para imóveis que apenas agrupam unidades (ex.: o prédio em si, não alugado diretamente).",
                verbose_name="Unidade Locável",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="uso",
            field=models.CharField(
                choices=[
                    ("residencial", "Residencial"),
                    ("comercial", "Comercial"),
                    ("misto", "Misto"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
                verbose_name="Uso",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="comissao_imobiliaria_percentual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual cobrado pela imobiliária sobre o encargo de aluguel. Gera despesa automática ao gerar a receita mensal.",
                max_digits=5,
                null=True,
                verbose_name="Taxa de Administração Imobiliária (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_fim",
            field=models.DateField(
                help_text="Data de término do prazo determinado original do contrato.",
                verbose_name="Data de Término Original",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="fiador",
            field=models.ForeignKey(
                blank=True,
                help_text='Campo legado. Para múltiplos fiadores, cadastre em "Partes do Contrato".',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_como_fiador",
                to="patrimonio.pessoa",
                verbose_name="Fiador (legado)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="imobiliaria",
            field=models.ForeignKey(
                blank=True,
                help_text='Campo legado. Pode também ser cadastrada em "Partes do Contrato".',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_como_imobiliaria",
                to="patrimonio.pessoa",
                verbose_name="Imobiliária (legado)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="locatario",
            field=models.ForeignKey(
                help_text='Campo legado. Para múltiplos locatários, cadastre em "Partes do Contrato".',
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos_como_locatario",
                to="patrimonio.pessoa",
                verbose_name="Locatário (legado)",
            ),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("locatario", "Locatário"),
                    ("fiador", "Fiador"),
                    ("fornecedor", "Fornecedor"),
                    ("imobiliaria", "Imobiliária"),
                    ("contador", "Contador"),
                    ("advogado", "Advogado"),
                    ("familiar", "Familiar"),
                    ("outro", "Outro"),
                ],
                default="outro",
                help_text='Classificação principal, usada apenas para busca e organização. Não restringe o papel da pessoa em contratos — a mesma pessoa pode ser locatária em um contrato e fiadora em outro (ver "Partes do Contrato").',
                max_length=20,
                verbose_name="Categoria Preferencial",
            ),
        ),
        migrations.CreateModel(
            name="ReajusteContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_reajuste", models.DateField(verbose_name="Data do Reajuste")),
                (
                    "indice",
                    models.CharField(
                        choices=[
                            ("ipca", "IPCA"),
                            ("igpm", "IGP-M"),
                            ("inpc", "INPC"),
                            ("fixo", "Fixo"),
                            ("outro", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Índice",
                    ),
                ),
                (
                    "percentual_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Percentual Aplicado (%)",
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Anterior (R$)",
                    ),
                ),
                (
                    "valor_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Novo (R$)"
                    ),
                ),
                (
                    "aplicado",
                    models.BooleanField(
                        default=False,
                        help_text="Ao marcar e salvar um reajuste novo como aplicado, o sistema atualiza o valor vigente do contrato e do encargo de aluguel automaticamente.",
                        verbose_name="Aplicado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reajustes",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reajuste de Contrato",
                "verbose_name_plural": "Reajustes de Contrato",
                "ordering": ["-data_reajuste"],
            },
        ),
        migrations.CreateModel(
            name="EncargoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("taxa_manutencao", "Taxa de Manutenção"),
                            ("seguro", "Seguro"),
                            ("agua_luz_comum", "Água/Luz Comum"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "periodicidade",
                    models.CharField(
                        choices=[
                            ("mensal", "Mensal"),
                            ("anual", "Anual"),
                            ("unico", "Único"),
                        ],
                        default="mensal",
                        max_length=20,
                        verbose_name="Periodicidade",
                    ),
                ),
                (
                    "data_inicio_cobranca",
                    models.DateField(
                        blank=True,
                        help_text="Se preenchida e posterior à competência, o encargo não é cobrado antes dessa data (útil para carência).",
                        null=True,
                        verbose_name="Início da Cobrança",
                    ),
                ),
                (
                    "data_fim_cobranca",
                    models.DateField(
                        blank=True,
                        help_text="Se preenchida e anterior à competência, o encargo deixa de ser cobrado a partir dessa data.",
                        null=True,
                        verbose_name="Fim da Cobrança",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encargos",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encargo do Contrato",
                "verbose_name_plural": "Encargos do Contrato",
                "ordering": ["contrato", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="ContratoParte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("locatario", "Locatário"),
                            ("fiador", "Fiador"),
                            ("representante", "Representante"),
                            ("conjuge", "Cônjuge"),
                            ("imobiliaria", "Imobiliária"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partes",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes_contratuais",
                        to="patrimonio.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte do Contrato",
                "verbose_name_plural": "Partes do Contrato",
                "ordering": ["contrato", "papel", "pessoa__nome"],
                "unique_together": {("contrato", "pessoa", "papel")},
            },
        ),
    ]
