# Generated by Django 4.2.30 on 2026-07-07 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patrimonio", "0005_migrar_encargo_aluguel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        help_text="Data de término do prazo determinado original do contrato.",
                        verbose_name="Data de Término Original",
                    ),
                ),
                (
                    "prazo_indeterminado",
                    models.BooleanField(
                        default=False,
                        help_text="Marque quando o contrato foi prorrogado por prazo indeterminado após o término original.",
                        verbose_name="Prazo Indeterminado",
                    ),
                ),
                (
                    "data_encerramento_real",
                    models.DateField(
                        blank=True,
                        help_text="Preencha apenas quando o contrato foi efetivamente encerrado (rescisão ou fim real da locação).",
                        null=True,
                        verbose_name="Data de Encerramento Real",
                    ),
                ),
                (
                    "valor_aluguel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor do Aluguel (R$)",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia de Vencimento",
                    ),
                ),
                (
                    "indice_reajuste",
                    models.CharField(
                        choices=[
                            ("ipca", "IPCA"),
                            ("igpm", "IGP-M"),
                            ("inpc", "INPC"),
                            ("fixo", "Fixo"),
                            ("outro", "Outro"),
                        ],
                        default="ipca",
                        max_length=10,
                        verbose_name="Índice de Reajuste",
                    ),
                ),
                (
                    "data_proximo_reajuste",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Próximo Reajuste"
                    ),
                ),
                (
                    "tipo_garantia",
                    models.CharField(
                        choices=[
                            ("caucao", "Caução"),
                            ("fiador", "Fiador"),
                            ("seguro_fianca", "Seguro Fiança"),
                            ("titulo_capitalizacao", "Título de Capitalização"),
                            ("sem_garantia", "Sem Garantia"),
                            ("outro", "Outro"),
                        ],
                        default="sem_garantia",
                        max_length=30,
                        verbose_name="Tipo de Garantia",
                    ),
                ),
                (
                    "comissao_imobiliaria_percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentual cobrado pela imobiliária sobre o encargo de aluguel. Gera despesa automática ao gerar a receita mensal.",
                        max_digits=5,
                        null=True,
                        verbose_name="Taxa de Administração Imobiliária (%)",
                    ),
                ),
                (
                    "multa_atraso_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentual de multa sobre o valor previsto, aplicado após os dias de carência.",
                        max_digits=6,
                        verbose_name="Multa por Atraso (%)",
                    ),
                ),
                (
                    "juros_mora_percentual_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentual de juros ao mês, calculado proporcionalmente aos dias de atraso (base 30 dias).",
                        max_digits=6,
                        verbose_name="Juros de Mora (% ao mês)",
                    ),
                ),
                (
                    "dias_carencia_multa",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Número de dias após o vencimento antes de multa/juros começarem a incidir.",
                        verbose_name="Dias de Carência para Multa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("encerrado", "Encerrado"),
                            ("rescindido", "Rescindido"),
                            ("suspenso", "Suspenso"),
                        ],
                        default="ativo",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contrato",
                "verbose_name_plural": "historical Contratos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContratoParte",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("locatario", "Locatário"),
                            ("fiador", "Fiador"),
                            ("representante", "Representante"),
                            ("conjuge", "Cônjuge"),
                            ("imobiliaria", "Imobiliária"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Parte do Contrato",
                "verbose_name_plural": "historical Partes do Contrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEncargoContrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("taxa_manutencao", "Taxa de Manutenção"),
                            ("seguro", "Seguro"),
                            ("agua_luz_comum", "Água/Luz Comum"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "periodicidade",
                    models.CharField(
                        choices=[
                            ("mensal", "Mensal"),
                            ("anual", "Anual"),
                            ("unico", "Único"),
                        ],
                        default="mensal",
                        max_length=20,
                        verbose_name="Periodicidade",
                    ),
                ),
                (
                    "data_inicio_cobranca",
                    models.DateField(
                        blank=True,
                        help_text="Se preenchida e posterior à competência, o encargo não é cobrado antes dessa data (útil para carência).",
                        null=True,
                        verbose_name="Início da Cobrança",
                    ),
                ),
                (
                    "data_fim_cobranca",
                    models.DateField(
                        blank=True,
                        help_text="Se preenchida e anterior à competência, o encargo deixa de ser cobrado a partir dessa data.",
                        null=True,
                        verbose_name="Fim da Cobrança",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Encargo do Contrato",
                "verbose_name_plural": "historical Encargos do Contrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalImovel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome / Identificação"
                    ),
                ),
                ("endereco", models.CharField(max_length=300, verbose_name="Endereço")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Matrícula"
                    ),
                ),
                (
                    "cartorio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cartório"
                    ),
                ),
                (
                    "inscricao_iptu",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inscrição IPTU"
                    ),
                ),
                (
                    "proprietario",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Proprietário(s)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alugado", "Alugado"),
                            ("vago", "Vago"),
                            ("em_manutencao", "Em Manutenção"),
                            ("vendido", "Vendido"),
                        ],
                        default="vago",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_imovel",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("sala_comercial", "Sala Comercial"),
                            ("loja", "Loja"),
                            ("predio", "Prédio"),
                            ("andar", "Andar"),
                            ("terreno", "Terreno"),
                            ("galpao", "Galpão"),
                            ("garagem", "Garagem"),
                            ("coworking", "Coworking"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                        verbose_name="Tipo de Imóvel",
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        choices=[
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                            ("misto", "Misto"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Uso",
                    ),
                ),
                (
                    "unidade_locavel",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para imóveis que apenas agrupam unidades (ex.: o prédio em si, não alugado diretamente).",
                        verbose_name="Unidade Locável",
                    ),
                ),
                (
                    "data_aquisicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aquisição"
                    ),
                ),
                (
                    "valor_aquisicao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor de Aquisição (R$)",
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Estimado Atual (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Imóvel",
                "verbose_name_plural": "historical Imóveis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalManutencao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("eletrica", "Elétrica"),
                            ("hidraulica", "Hidráulica"),
                            ("pintura", "Pintura"),
                            ("reforma", "Reforma"),
                            ("limpeza", "Limpeza"),
                            ("telhado", "Telhado"),
                            ("estrutural", "Estrutural"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateField(verbose_name="Data da Solicitação"),
                ),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Estimado (R$)",
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Final (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("orcamento_recebido", "Orçamento Recebido"),
                            ("aprovada", "Aprovada"),
                            ("em_execucao", "Em Execução"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="solicitada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Manutenção",
                "verbose_name_plural": "historical Manutenções",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPessoa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome / Razão Social"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("locatario", "Locatário"),
                            ("fiador", "Fiador"),
                            ("fornecedor", "Fornecedor"),
                            ("imobiliaria", "Imobiliária"),
                            ("contador", "Contador"),
                            ("advogado", "Advogado"),
                            ("familiar", "Familiar"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        help_text='Classificação principal, usada apenas para busca e organização. Não restringe o papel da pessoa em contratos — a mesma pessoa pode ser locatária em um contrato e fiadora em outro (ver "Partes do Contrato").',
                        max_length=20,
                        verbose_name="Categoria Preferencial",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Endereço"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pessoa",
                "verbose_name_plural": "historical Pessoas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReajusteContrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("data_reajuste", models.DateField(verbose_name="Data do Reajuste")),
                (
                    "indice",
                    models.CharField(
                        choices=[
                            ("ipca", "IPCA"),
                            ("igpm", "IGP-M"),
                            ("inpc", "INPC"),
                            ("fixo", "Fixo"),
                            ("outro", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Índice",
                    ),
                ),
                (
                    "percentual_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Percentual Aplicado (%)",
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Anterior (R$)",
                    ),
                ),
                (
                    "valor_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Novo (R$)"
                    ),
                ),
                (
                    "aplicado",
                    models.BooleanField(
                        default=False,
                        help_text="Ao marcar e salvar um reajuste novo como aplicado, o sistema atualiza o valor vigente do contrato e do encargo de aluguel automaticamente.",
                        verbose_name="Aplicado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Reajuste de Contrato",
                "verbose_name_plural": "historical Reajustes de Contrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="encargocontrato",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True), ("tipo", "aluguel")),
                fields=("contrato",),
                name="unico_encargo_aluguel_ativo_por_contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalreajustecontrato",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalreajustecontrato",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpessoa",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmanutencao",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.pessoa",
                verbose_name="Fornecedor / Prestador",
            ),
        ),
        migrations.AddField(
            model_name="historicalmanutencao",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmanutencao",
            name="imovel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.imovel",
                verbose_name="Imóvel",
            ),
        ),
        migrations.AddField(
            model_name="historicalimovel",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalimovel",
            name="imovel_pai",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Preencha quando este imóvel for uma unidade vinculada a um prédio/imóvel maior (ex.: andar ou sala de um prédio).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.imovel",
                verbose_name="Imóvel Pai",
            ),
        ),
        migrations.AddField(
            model_name="historicalencargocontrato",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalencargocontrato",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoparte",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoparte",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoparte",
            name="pessoa",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.pessoa",
                verbose_name="Pessoa",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="fiador",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Campo legado. Para múltiplos fiadores, cadastre em "Partes do Contrato".',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.pessoa",
                verbose_name="Fiador (legado)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="imobiliaria",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Campo legado. Pode também ser cadastrada em "Partes do Contrato".',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.pessoa",
                verbose_name="Imobiliária (legado)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="imovel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.imovel",
                verbose_name="Imóvel",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="locatario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Campo legado. Para múltiplos locatários, cadastre em "Partes do Contrato".',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patrimonio.pessoa",
                verbose_name="Locatário (legado)",
            ),
        ),
    ]
