# Generated by Django 4.2.30 on 2026-07-10 13:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0006_historicalcontrato_historicalcontratoparte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpessoa",
            name="cpf_cnpj_normalizado",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Preenchido automaticamente — usado para impedir cadastros duplicados.",
                max_length=14,
                verbose_name="CPF/CNPJ (somente dígitos)",
            ),
        ),
        migrations.AddField(
            model_name="historicalreajustecontrato",
            name="aplicado_em",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Preenchido pelo sistema no momento da aplicação — impede reaplicação.",
                null=True,
                verbose_name="Aplicado em",
            ),
        ),
        migrations.AddField(
            model_name="historicalreajustecontrato",
            name="periodo_indice",
            field=models.CharField(
                blank=True,
                help_text='Competências usadas na sugestão automática (ex.: "06/2023 a 05/2024").',
                max_length=40,
                verbose_name="Período do Índice",
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="cpf_cnpj_normalizado",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Preenchido automaticamente — usado para impedir cadastros duplicados.",
                max_length=14,
                verbose_name="CPF/CNPJ (somente dígitos)",
            ),
        ),
        migrations.AddField(
            model_name="reajustecontrato",
            name="aplicado_em",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Preenchido pelo sistema no momento da aplicação — impede reaplicação.",
                null=True,
                verbose_name="Aplicado em",
            ),
        ),
        migrations.AddField(
            model_name="reajustecontrato",
            name="periodo_indice",
            field=models.CharField(
                blank=True,
                help_text='Competências usadas na sugestão automática (ex.: "06/2023 a 05/2024").',
                max_length=40,
                verbose_name="Período do Índice",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="comissao_imobiliaria_percentual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual cobrado pela imobiliária sobre o encargo de aluguel. Gera despesa automática ao gerar a receita mensal.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Taxa de Administração Imobiliária (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="juros_mora_percentual_mes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de juros ao mês, calculado proporcionalmente aos dias de atraso (base 30 dias).",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Juros de Mora (% ao mês)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="multa_atraso_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de multa sobre o valor previsto, aplicado após os dias de carência.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Multa por Atraso (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_aluguel",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor do Aluguel (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrato",
            name="comissao_imobiliaria_percentual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual cobrado pela imobiliária sobre o encargo de aluguel. Gera despesa automática ao gerar a receita mensal.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Taxa de Administração Imobiliária (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrato",
            name="juros_mora_percentual_mes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de juros ao mês, calculado proporcionalmente aos dias de atraso (base 30 dias).",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Juros de Mora (% ao mês)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrato",
            name="multa_atraso_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de multa sobre o valor previsto, aplicado após os dias de carência.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Multa por Atraso (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrato",
            name="valor_aluguel",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor do Aluguel (R$)",
            ),
        ),
    ]
