# Generated by Django 4.2.30 on 2026-07-11 05:07
"""
Unicidade de CPF/CNPJ no banco.

Antes de criar a constraint, verifica duplicidades preexistentes em
cpf_cnpj_normalizado (não vazio). Se houver, a migration é INTERROMPIDA com a
lista de IDs/nomes conflitantes — nenhum cadastro é apagado ou mesclado
automaticamente: a escolha de qual registro mantém o documento é do usuário.
Corrija os cadastros (Admin → Pessoas) e rode `migrate` novamente.
"""
from django.db import migrations, models


def verificar_duplicidades(apps, schema_editor):
    Pessoa = apps.get_model('patrimonio', 'Pessoa')
    duplicados = (
        Pessoa.objects.exclude(cpf_cnpj_normalizado='')
        .values('cpf_cnpj_normalizado')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    conflitos = []
    for grupo in duplicados:
        pessoas = Pessoa.objects.filter(
            cpf_cnpj_normalizado=grupo['cpf_cnpj_normalizado']
        ).values_list('id', 'nome')
        detalhe = ', '.join(f'#{pk} {nome}' for pk, nome in pessoas)
        conflitos.append(f"CPF/CNPJ {grupo['cpf_cnpj_normalizado']}: {detalhe}")
    if conflitos:
        raise RuntimeError(
            'Não foi possível criar a unicidade de CPF/CNPJ: existem cadastros '
            'duplicados que precisam de correção MANUAL (nenhum registro foi '
            'alterado). Ajuste no Admin → Pessoas e rode `migrate` de novo. '
            'Conflitos encontrados: ' + ' | '.join(conflitos)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0008_backfill_aplicado_em_e_cpf_normalizado"),
    ]

    operations = [
        migrations.RunPython(verificar_duplicidades, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pessoa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf_cnpj_normalizado", ""), _negated=True),
                fields=("cpf_cnpj_normalizado",),
                name="pessoa_cpf_cnpj_normalizado_unico_quando_preenchido",
            ),
        ),
    ]
