# Generated by Django 4.2.30 on 2026-07-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "patrimonio",
            "0009_pessoa_pessoa_cpf_cnpj_normalizado_unico_quando_preenchido",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reajustecontrato",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reajustes",
                to="patrimonio.contrato",
                verbose_name="Contrato",
            ),
        ),
    ]
