# Generated by Django 4.2.30 on 2026-07-13 00:07
"""
Consistência entre aplicado × aplicado_em em ReajusteContrato (item 5,
rodada de fechamento estrutural): únicos estados válidos são
(aplicado=False, aplicado_em=NULL) ou (aplicado=True, aplicado_em
preenchido) — nunca uma combinação intermediária.

Antes de criar a constraint, verifica se já existem registros que a
violariam. Se houver, a migration é INTERROMPIDA com uma mensagem listando
IDs, contrato, aplicado e aplicado_em em conflito — nenhum dado é alterado
automaticamente; corrija manualmente (Admin/shell) e rode `migrate` de novo.
Mesmo padrão RunPython pre-check de financeiro/migrations/0008_validacoes_despesa.py.
"""
from django.db import migrations, models


def verificar_dados_invalidos(apps, schema_editor):
    ReajusteContrato = apps.get_model('patrimonio', 'ReajusteContrato')

    conflitos = []

    aplicado_sem_data = ReajusteContrato.objects.filter(
        aplicado=True, aplicado_em__isnull=True,
    ).values_list('id', 'contrato_id')
    for pk, contrato_id in aplicado_sem_data:
        conflitos.append(f'ReajusteContrato #{pk} (contrato #{contrato_id}): aplicado=True, aplicado_em=NULL')

    nao_aplicado_com_data = ReajusteContrato.objects.filter(
        aplicado=False, aplicado_em__isnull=False,
    ).values_list('id', 'contrato_id', 'aplicado_em')
    for pk, contrato_id, aplicado_em in nao_aplicado_com_data:
        conflitos.append(
            f'ReajusteContrato #{pk} (contrato #{contrato_id}): aplicado=False, aplicado_em={aplicado_em}'
        )

    if conflitos:
        raise RuntimeError(
            'Não foi possível criar a validação de consistência de ReajusteContrato: existem '
            'registros que violariam a nova regra (aplicado=False,aplicado_em=NULL ou '
            'aplicado=True,aplicado_em preenchido) e precisam de correção MANUAL (nenhum dado '
            'foi alterado). Ajuste no Admin/shell e rode `migrate` de novo. '
            'Conflitos encontrados: ' + ' | '.join(conflitos)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0010_reajustecontrato_contrato_protect"),
    ]

    operations = [
        migrations.RunPython(verificar_dados_invalidos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reajustecontrato",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("aplicado", False), ("aplicado_em__isnull", True)),
                    models.Q(("aplicado", True), ("aplicado_em__isnull", False)),
                    _connector="OR",
                ),
                name="reajustecontrato_aplicado_aplicado_em_coerentes",
            ),
        ),
    ]
