# Generated by Django 4.2.16 on 2026-06-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patrimonio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "data_fechamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Fechamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "enviado_contabilidade",
                    models.BooleanField(
                        default=False, verbose_name="Enviado à Contabilidade"
                    ),
                ),
                (
                    "data_envio_contabilidade",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Envio à Contabilidade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Fechamento Mensal",
                "verbose_name_plural": "Fechamentos Mensais",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("manutencao", "Manutenção"),
                            ("seguro", "Seguro"),
                            ("taxa_bancaria", "Taxa Bancária"),
                            ("contabilidade", "Contabilidade"),
                            ("advocacia", "Advocacia"),
                            ("comissao_imobiliaria", "Comissão Imobiliária"),
                            ("obra_reforma", "Obra / Reforma"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "competencia_mes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "competencia_ano",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ano de Competência"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prevista", "Prevista"),
                            ("paga", "Paga"),
                            ("atrasada", "Atrasada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="prevista",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patrimonio.pessoa",
                        verbose_name="Fornecedor / Credor",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="ReceitaAluguel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia_mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "competencia_ano",
                    models.PositiveSmallIntegerField(verbose_name="Ano de Competência"),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor_previsto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Previsto (R$)",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Recebido (R$)",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previsto", "Previsto"),
                            ("recebido", "Recebido"),
                            ("atrasado", "Atrasado"),
                            ("parcial", "Parcial"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="previsto",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Multa (R$)",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Juros (R$)",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita de Aluguel",
                "verbose_name_plural": "Receitas de Aluguel",
                "ordering": ["-competencia_ano", "-competencia_mes"],
                "unique_together": {("contrato", "competencia_mes", "competencia_ano")},
            },
        ),
    ]
