# Generated by Django 4.2.16 on 2026-06-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0002_dia_vencimento_validators"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receitaaluguel",
            name="imovel",
            field=models.ForeignKey(
                help_text="Preenchido automaticamente pelo contrato. Não altere manualmente.",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.imovel",
                verbose_name="Imóvel",
            ),
        ),
    ]
