# Generated by Django 4.2.16 on 2026-07-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0003_contrato_data_encerramento_real_and_more"),
        ("financeiro", "0002_alter_receitaaluguel_imovel"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despesas",
                to="patrimonio.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="origem_automatica",
            field=models.BooleanField(
                default=False,
                help_text="Marcado pelo sistema quando a despesa é criada automaticamente (ex.: taxa de administração).",
                verbose_name="Gerada Automaticamente",
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="receita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despesas_vinculadas",
                to="financeiro.receitaaluguel",
                verbose_name="Receita de Aluguel Vinculada",
            ),
        ),
        migrations.CreateModel(
            name="ReceitaAluguelItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30, verbose_name="Tipo")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Receita",
                "verbose_name_plural": "Itens da Receita",
                "ordering": ["id"],
            },
        ),
    ]
