# Generated by Django 4.2.30 on 2026-07-07 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0006_historicalcontrato_historicalcontratoparte_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0003_despesa_contrato_despesa_origem_automatica_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReceitaAluguel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "competencia_mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "competencia_ano",
                    models.PositiveSmallIntegerField(verbose_name="Ano de Competência"),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor_previsto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Previsto (R$)",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Recebido (R$)",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previsto", "Previsto"),
                            ("recebido", "Recebido"),
                            ("atrasado", "Atrasado"),
                            ("parcial", "Parcial"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="previsto",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Multa (R$)",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Juros (R$)",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Preenchido automaticamente pelo contrato. Não altere manualmente.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receita de Aluguel",
                "verbose_name_plural": "historical Receitas de Aluguel",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFechamentoMensal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "data_fechamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Fechamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "enviado_contabilidade",
                    models.BooleanField(
                        default=False, verbose_name="Enviado à Contabilidade"
                    ),
                ),
                (
                    "data_envio_contabilidade",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Envio à Contabilidade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fechamento Mensal",
                "verbose_name_plural": "historical Fechamentos Mensais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDespesa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "origem_automatica",
                    models.BooleanField(
                        default=False,
                        help_text="Marcado pelo sistema quando a despesa é criada automaticamente (ex.: taxa de administração).",
                        verbose_name="Gerada Automaticamente",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("iptu", "IPTU"),
                            ("condominio", "Condomínio"),
                            ("manutencao", "Manutenção"),
                            ("seguro", "Seguro"),
                            ("taxa_bancaria", "Taxa Bancária"),
                            ("contabilidade", "Contabilidade"),
                            ("advocacia", "Advocacia"),
                            ("comissao_imobiliaria", "Comissão Imobiliária"),
                            ("obra_reforma", "Obra / Reforma"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "competencia_mes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "competencia_ano",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ano de Competência"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prevista", "Prevista"),
                            ("paga", "Paga"),
                            ("atrasada", "Atrasada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="prevista",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.pessoa",
                        verbose_name="Fornecedor / Credor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patrimonio.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita de Aluguel Vinculada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Despesa",
                "verbose_name_plural": "historical Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
