# Generated by Django 4.2.30 on 2026-07-10 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conciliacao", "0002_contabancaria_bank_id_and_more"),
        (
            "financeiro",
            "0004_historicalreceitaaluguel_historicalfechamentomensal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecebimentoReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(verbose_name="Data do Recebimento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("conciliacao", "Conciliação Bancária"),
                            ("migracao", "Migração (histórico)"),
                        ],
                        default="manual",
                        max_length=15,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recebimentos",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita",
                    ),
                ),
                (
                    "transacao_extrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos",
                        to="conciliacao.transacaoextrato",
                        verbose_name="Transação do Extrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento da Receita",
                "verbose_name_plural": "Recebimentos da Receita",
                "ordering": ["data_recebimento", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRecebimentoReceita",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(verbose_name="Data do Recebimento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("conciliacao", "Conciliação Bancária"),
                            ("migracao", "Migração (histórico)"),
                        ],
                        default="manual",
                        max_length=15,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="financeiro.receitaaluguel",
                        verbose_name="Receita",
                    ),
                ),
                (
                    "transacao_extrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="conciliacao.transacaoextrato",
                        verbose_name="Transação do Extrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recebimento da Receita",
                "verbose_name_plural": "historical Recebimentos da Receita",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
