# Generated by Django 4.2.30 on 2026-07-11 06:07
"""
Validações monetárias no banco (item 15): multa/juros/desconto >= 0 em
ReceitaAluguel, desconto não pode exceder o total devido, e valor > 0 em
RecebimentoReceita (reforça a mesma regra do item 3).

Antes de criar as constraints, verifica se já existem dados que as
violariam. Se houver, a migration é INTERROMPIDA com uma mensagem listando
IDs e valores em conflito — nenhum dado é alterado automaticamente; corrija
manualmente (Admin) e rode `migrate` novamente.
"""
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


def verificar_dados_invalidos(apps, schema_editor):
    ReceitaAluguel = apps.get_model('financeiro', 'ReceitaAluguel')
    RecebimentoReceita = apps.get_model('financeiro', 'RecebimentoReceita')

    conflitos = []

    negativos = ReceitaAluguel.objects.filter(
        models.Q(multa__lt=0) | models.Q(juros__lt=0) | models.Q(desconto__lt=0)
    ).values_list('id', 'multa', 'juros', 'desconto')
    for pk, multa, juros, desconto in negativos:
        conflitos.append(
            f'ReceitaAluguel #{pk}: multa={multa}, juros={juros}, desconto={desconto} (valor negativo)'
        )

    excedentes = ReceitaAluguel.objects.filter(
        desconto__gt=models.F('valor_previsto') + models.F('multa') + models.F('juros')
    ).values_list('id', 'valor_previsto', 'multa', 'juros', 'desconto')
    for pk, previsto, multa, juros, desconto in excedentes:
        conflitos.append(
            f'ReceitaAluguel #{pk}: desconto={desconto} excede previsto+multa+juros '
            f'({previsto}+{multa}+{juros})'
        )

    invalidos = RecebimentoReceita.objects.filter(valor__lte=0).values_list('id', 'valor')
    for pk, valor in invalidos:
        conflitos.append(f'RecebimentoReceita #{pk}: valor={valor} (deve ser > 0)')

    if conflitos:
        raise RuntimeError(
            'Não foi possível criar as validações monetárias: existem registros que '
            'violariam as novas regras e precisam de correção MANUAL (nenhum dado foi '
            'alterado). Ajuste no Admin e rode `migrate` de novo. '
            'Conflitos encontrados: ' + ' | '.join(conflitos)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_migrar_recebimentos_iniciais"),
    ]

    operations = [
        migrations.RunPython(verificar_dados_invalidos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicalrecebimentoreceita",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceitaaluguel",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Desconto (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceitaaluguel",
            name="juros",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Juros (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceitaaluguel",
            name="multa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Multa (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="recebimentoreceita",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="receitaaluguel",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Desconto (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="receitaaluguel",
            name="juros",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Juros (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="receitaaluguel",
            name="multa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Multa (R$)",
            ),
        ),
        migrations.AddConstraint(
            model_name="recebimentoreceita",
            constraint=models.CheckConstraint(
                check=models.Q(("valor__gt", 0)),
                name="recebimentoreceita_valor_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitaaluguel",
            constraint=models.CheckConstraint(
                check=models.Q(("multa__gte", 0)),
                name="receitaaluguel_multa_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitaaluguel",
            constraint=models.CheckConstraint(
                check=models.Q(("juros__gte", 0)),
                name="receitaaluguel_juros_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitaaluguel",
            constraint=models.CheckConstraint(
                check=models.Q(("desconto__gte", 0)),
                name="receitaaluguel_desconto_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitaaluguel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "desconto__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("valor_previsto"), "+", models.F("multa")
                            ),
                            "+",
                            models.F("juros"),
                        ),
                    )
                ),
                name="receitaaluguel_desconto_nao_excede_total_devido",
            ),
        ),
    ]
