# Generated by Django 4.2.30 on 2026-07-11 21:17
"""
Validações de integridade em Despesa (item 10, rodada pós-revisão): valor > 0
e coerência entre status e data_pagamento ('paga' sempre tem data; as demais
nunca têm).

Antes de criar as constraints, verifica se já existem dados que as
violariam. Se houver, a migration é INTERROMPIDA com uma mensagem listando
IDs e valores em conflito — nenhum dado é alterado automaticamente; corrija
manualmente (Admin) e rode `migrate` novamente.
"""
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def verificar_dados_invalidos(apps, schema_editor):
    Despesa = apps.get_model('financeiro', 'Despesa')

    conflitos = []

    invalidas = Despesa.objects.filter(valor__lte=0).values_list('id', 'valor')
    for pk, valor in invalidas:
        conflitos.append(f'Despesa #{pk}: valor={valor} (deve ser > 0)')

    paga_sem_data = Despesa.objects.filter(
        status='paga', data_pagamento__isnull=True
    ).values_list('id', flat=True)
    for pk in paga_sem_data:
        conflitos.append(f'Despesa #{pk}: status=paga sem data_pagamento')

    nao_paga_com_data = Despesa.objects.exclude(status='paga').filter(
        data_pagamento__isnull=False
    ).values_list('id', 'status', 'data_pagamento')
    for pk, status, data_pagamento in nao_paga_com_data:
        conflitos.append(f'Despesa #{pk}: status={status} com data_pagamento={data_pagamento}')

    if conflitos:
        raise RuntimeError(
            'Não foi possível criar as validações de Despesa: existem registros que '
            'violariam as novas regras e precisam de correção MANUAL (nenhum dado foi '
            'alterado). Ajuste no Admin e rode `migrate` de novo. '
            'Conflitos encontrados: ' + ' | '.join(conflitos)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_validacoes_monetarias"),
    ]

    operations = [
        migrations.RunPython(verificar_dados_invalidos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="despesa",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldespesa",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor (R$)",
            ),
        ),
        migrations.AddConstraint(
            model_name="despesa",
            constraint=models.CheckConstraint(
                check=models.Q(("valor__gt", 0)), name="despesa_valor_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="despesa",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("data_pagamento__isnull", False), ("status", "paga")),
                    models.Q(
                        models.Q(("status", "paga"), _negated=True),
                        ("data_pagamento__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="despesa_status_data_pagamento_coerentes",
            ),
        ),
    ]
